# Generated by Django 4.2.13 on 2024-06-22 07:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
    ]
